name: Terraform Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'
        type: string
      environment:
        description: 'Environment to deploy to (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
        type: string
      auto_apply:
        description: 'Automatically apply the changes'
        required: true
        default: true
        type: boolean

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Update this to your preferred AWS region

      - name: Initialize Terraform
        run: terraform init -input=false
        working-directory: terraform/iam

      - name: Plan Terraform
        run: terraform plan -input=false -out=tfplan -var="env=${{ github.event.inputs.env }}"
        working-directory: terraform/iam

      - name: Apply Terraform
        
        run: terraform apply "tfplan" -var="env=${{ github.event.inputs.env }}"
        working-directory: terraform/iam
